version: '2'
services:
    snorlax-app:
        image: snorlax
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://snorlax-postgresql:5432/Snorlax
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    snorlax-postgresql:
        extends:
            file: postgresql.yml
            service: snorlax-postgresql
